services:
  - type: web
    name: sarvtribe-web
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sarvtribe-db
          property: connectionString
      - key: NEXTAUTH_URL
        value: https://sarvtribe-web.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: EMAIL_SERVER_HOST
        value: smtp.gmail.com
      - key: EMAIL_SERVER_PORT
        value: 587
      - key: EMAIL_SERVER_USER
        sync: false
      - key: EMAIL_SERVER_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: NEXT_PUBLIC_PIXO_API_KEY
        sync: false
      - key: NEXT_PUBLIC_SOCKET_URL
        value: https://sarvtribe-socket.onrender.com

  - type: web
    name: sarvtribe-socket
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node socket-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://sarvtribe-web.onrender.com

databases:
  - name: sarvtribe-db
    plan: starter
